#!/bin/bash
set -e

if [ "$1" = "purge" ]; then
  echo "Removing config files..."
  rm -rf /home/yurchyk/.config/todo-conf
  echo "Config folder was removed!"
  // TODO: Read first from conf file where it is located
  echo "Removing todo storage..."
  rm -f /home/yurchyk/.todo
  rm -f /home/yurchyk/.todo.db
  echo "Storage files were removed!"
fi