#!/bin/bash

set -e

echo "Configuring todo-cli..."

config_path=""

if [ -z "$XDG_CONFIG_HOME" ]; then
  config_path="/etc/todo-cli"
else
  config_path="${XDG_CONFIG_HOME}/todo-cli"
fi

mkdir -p "$(dirname "$config_path")"

DEFAULT_STORAGE_TYPE="FILE"
DEFAULT_STORAGE_PATH=$config_path

echo "Enter storage type that you want to use FILE(default) or SQLITE:"
read -r storage_type
echo "Enter path to your storage (default ${DEFAULT_STORAGE_PATH}):"
read -r storage_path

if [ -z "$storage_type" ]; then
  storage_type=$DEFAULT_STORAGE_TYPE
fi

if [ -z "$storage_path" ]; then
  storage_path=$DEFAULT_STORAGE_PATH
fi

cat << EOF > "$config_path/todo.cfg"
STORAGE_TYPE=$storage_type
STORAGE_PATH=$storage_path
EOF

echo "Configuration created at $config_path/todo.cfg"

