#!/bin/bash

set -e

DEFAULT_CONFIG_PATH="/home/yurchyk/.config/todo-conf"

echo "Configuring todo-cli..."
echo "Enter the path to your configuration folder or use default location(${DEFAULT_CONFIG_PATH})":
read -r config_path

if [ -z "$config_path" ]; then
  config_path=$DEFAULT_CONFIG_PATH
fi

mkdir -p "$(dirname "$config_path")"

DEFAULT_STORAGE_TYPE="FILE"
DEFAULT_STORAGE_PATH="/home/yurchyk"

echo "Enter storage type that you want to use FILE(default) or SQLITE:"
read -r storage_type
echo "Enter path to your storage (default ${DEFAULT_STORAGE_PATH}):"
read -r storage_path

if [ -z "$storage_type" ]; then
  storage_type=$DEFAULT_STORAGE_TYPE
fi

if [ -z "$storage_path" ]; then
  storage_path=$DEFAULT_STORAGE_PATH
fi

cat << EOF > "$config_path/.todo-conf"
STORAGE_TYPE=$storage_type
STORAGE_PATH=$storage_path
EOF

echo "Configuration created at $config_path/.todo-cli"

